# Generated by Django 5.2.17 on 2026-10-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0010_auto_20250214_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('future', 'Future'), ('draft', 'Draft'), ('submitted', 'Received'), ('amendment_required', 'Amendment Required'), ('amended', 'Amended'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='future', max_length=20),
        ),
    ]
