# Generated by Django 5.2.17 on 2026-09-29 07:01

import wildlifelicensing.apps.main.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0051_add_nomostaxonomy_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessorgroupmembers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nomostaxonomy',
            options={'verbose_name_plural': 'NOMOS Taxonomies'},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=wildlifelicensing.apps.main.storage.PrivateFileSystemStorage(), upload_to='%Y/%m/%d'),
        ),
    ]
