# Generated by Django 5.2.17 on 2026-10-01 01:44

import wildlifelicensing.apps.main.models
import wildlifelicensing.apps.main.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0052_alter_assessorgroupmembers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=wildlifelicensing.apps.main.storage.PrivateFileSystemStorage(), upload_to=wildlifelicensing.apps.main.models.document_upload_path),
        ),
    ]
